theme: minima 

footer_text: "Thank you for visiting my website!"

contact_email: "veeraya.lek@gmail.com"

social_media:
  linkedin: "www.linkedin.com/in/veeraya-lekchaoum-2351bb305"
  github: "https://github.com/VaLin4637"
